import { useStorage } from "../providers/Web3StorageProvider";
import DropArea from "../components/DropArea";
import { useState } from "react";

const CreateProfile = () => {
  const [file, setFile] = useState<File | null>(null);

  function fileChange(newFile: File) {
    setFile(newFile);
  }

  return (
    <div>
      <title>Upload File</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <div className="flex justify-between items-center flex-col">
        <div className="h-52 w-full rounded bg-gray-100 mb-16 flex justify-center items-center">
          <p>SOME CONTENT</p>
        </div>
      </div>
      <h1>Upload File to Web3.Storage</h1>
      <DropArea />
    </div>
  );
};

export default CreateProfile;
