import DropArea from '../components/DropArea';

const CreateProfile = () => {
  return (
    <div>
      <title>Upload File</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
      <div className="flex justify-between items-center flex-col">
        <div className="h-52 w-full rounded bg-gray-800 mb-16 flex justify-center items-center">
          <h1>Mint Profile</h1>
        </div>
      </div>

      <DropArea />
    </div>
  );
};

export default CreateProfile;
